import json
from pathlib import Path

from skelly.strategies.base import BackendStrategy
from skelly.core.models import Architecture, ProjectConfig
from skelly.core.template_renderer import render_to_file


# Template → output path mapping for hexagonal architecture
_HEXAGONAL_TEMPLATES = [
    # Domain
    ("express/hexagonal/domain/Example.js.j2", "src/domain/model/Example.js"),
    ("express/hexagonal/domain/index.js.j2", "src/domain/model/index.js"),
    # Application - Ports (In)
    ("express/hexagonal/application/GetExampleUseCase.js.j2", "src/application/port/in/GetExampleUseCase.js"),
    ("express/hexagonal/application/CreateExampleUseCase.js.j2", "src/application/port/in/CreateExampleUseCase.js"),
    ("express/hexagonal/application/port_in_index.js.j2", "src/application/port/in/index.js"),
    # Application - Ports (Out)
    ("express/hexagonal/application/ExampleRepository.js.j2", "src/application/port/out/ExampleRepository.js"),
    ("express/hexagonal/application/port_out_index.js.j2", "src/application/port/out/index.js"),
    # Application - Service
    ("express/hexagonal/application/ExampleService.js.j2", "src/application/service/ExampleService.js"),
    ("express/hexagonal/application/service_index.js.j2", "src/application/service/index.js"),
    # Adapter - Web (Input)
    ("express/hexagonal/adapter/ExampleController.js.j2", "src/adapter/in/web/ExampleController.js"),
    ("express/hexagonal/adapter/web_index.js.j2", "src/adapter/in/web/index.js"),
    # Adapter - Persistence (Output)
    ("express/hexagonal/adapter/ExamplePersistenceAdapter.js.j2", "src/adapter/out/persistence/ExamplePersistenceAdapter.js"),
    ("express/hexagonal/adapter/persistence_index.js.j2", "src/adapter/out/persistence/index.js"),
    # Infrastructure
    ("express/hexagonal/index.js.j2", "src/index.js"),
    ("express/hexagonal/config_index.js.j2", "src/infrastructure/config/index.js"),
]


class ExpressBackend(BackendStrategy):
    """Express.js backend with npm."""

    def get_folders(self) -> list[str]:
        return []

    def get_name(self) -> str:
        return "Express.js"

    def create_config_files(self, config: ProjectConfig, base_path: Path) -> None:
        server_path = base_path / "server"
        dependencies = {"express": "^4.18.2"}

        for lib_entry in config.backend_libraries:
            libs = lib_entry.split(" ")
            for lib in libs:
                if lib.strip():
                    dependencies[lib.strip()] = "latest"

        package_json = {
            "name": f"{config.name.lower().replace(' ', '-')}-server",
            "version": "0.1.0",
            "type": "module",
            "description": "Generated by Skelly",
            "main": "src/index.js",
            "scripts": {
                "start": "node src/index.js",
                "dev": "nodemon src/index.js",
            },
            "dependencies": dependencies,
        }

        package_json_path = server_path / "package.json"
        with open(package_json_path, "w") as f:
            json.dump(package_json, f, indent=2)

        print(f"[cyan]Created server/package.json with dependencies: {', '.join(dependencies.keys())}[/cyan]")

        if config.architecture == Architecture.HEXAGONAL.value:
            self._generate_hexagonal_example(base_path)

    def _generate_hexagonal_example(self, base_path: Path) -> None:
        """Generate example code with domain/application/adapter structure."""
        server_path = base_path / "server"

        print("[cyan]Generating hexagonal architecture example (domain/application/adapter)...[/cyan]")

        for template_path, output_rel in _HEXAGONAL_TEMPLATES:
            render_to_file(template_path, server_path / output_rel)

        print("[green]Generated hexagonal architecture example with Example entity![/green]")
        print("[dim]  - Domain: Example entity[/dim]")
        print("[dim]  - Ports: GetExampleUseCase, CreateExampleUseCase, ExampleRepository[/dim]")
        print("[dim]  - Adapters: ExampleController, ExamplePersistenceAdapter[/dim]")
        print("[dim]  - Entry: src/index.js with dependency injection[/dim]")

    def install_dependencies(self, base_path: Path) -> None:
        server_path = base_path / "server"
        print("[yellow]Running npm install for server...[/yellow]")
        self._run_command(
            ["npm", "install"],
            cwd=server_path,
            success_msg="Server dependencies installed successfully!",
            fail_msg="Failed to install dependencies. Do you have 'npm' installed?",
        )
