import json
import subprocess
from typing import List
from pathlib import Path

from skelly.strategies.base import BackendStrategy
from skelly.core.models import ProjectConfig


class ExpressBackend(BackendStrategy):
    """Express.js backend with npm."""

    def get_folders(self) -> List[str]:
        return []

    def get_name(self) -> str:
        return "Express.js"

    def create_config_files(self, config: ProjectConfig, base_path: Path) -> None:
        dependencies = {"express": "^4.18.2"}

        for lib_entry in config.backend_libraries:
            libs = lib_entry.split(" ")
            for lib in libs:
                if lib.strip():
                    dependencies[lib.strip()] = "latest"

        package_json = {
            "name": config.name.lower().replace(" ", "-"),
            "version": "0.1.0",
            "description": "Generated by Skelly",
            "main": "src/index.js",
            "scripts": {
                "start": "node src/index.js",
                "dev": "nodemon src/index.js"
            },
            "dependencies": dependencies
        }

        package_json_path = base_path / "package.json"
        with open(package_json_path, "w") as f:
            json.dump(package_json, f, indent=2)

        print(f"[cyan]Created package.json with dependencies: {', '.join(dependencies.keys())}[/cyan]")

    def install_dependencies(self, base_path: Path) -> None:
        print("[yellow]Running npm install...[/yellow]")
        try:
            subprocess.run(["npm", "install"], cwd=base_path, shell=True, check=True)
            print("[green]Dependencies installed successfully![/green]")
        except subprocess.CalledProcessError:
            print("[red]Failed to install dependencies. Do you have 'npm' installed?[/red]")
        except Exception as e:
            print(f"[red]Error during installation: {e}[/red]")
