import json
import subprocess
from typing import List
from pathlib import Path

from skelly.strategies.base import BackendStrategy
from skelly.core.models import ProjectConfig


class ExpressBackend(BackendStrategy):
    """Express.js backend with npm."""

    def get_folders(self) -> List[str]:
        return []

    def get_name(self) -> str:
        return "Express.js"

    def create_config_files(self, config: ProjectConfig, base_path: Path) -> None:
        server_path = base_path / "server"
        dependencies = {"express": "^4.18.2"}

        for lib_entry in config.backend_libraries:
            libs = lib_entry.split(" ")
            for lib in libs:
                if lib.strip():
                    dependencies[lib.strip()] = "latest"

        package_json = {
            "name": f"{config.name.lower().replace(' ', '-')}-server",
            "version": "0.1.0",
            "type": "module",
            "description": "Generated by Skelly",
            "main": "src/index.js",
            "scripts": {
                "start": "node src/index.js",
                "dev": "nodemon src/index.js"
            },
            "dependencies": dependencies
        }

        package_json_path = server_path / "package.json"
        with open(package_json_path, "w") as f:
            json.dump(package_json, f, indent=2)

        print(f"[cyan]Created server/package.json with dependencies: {', '.join(dependencies.keys())}[/cyan]")

        if config.architecture == "Hexagonal Architecture":
            self._generate_hexagonal_example(config, base_path)

    def _generate_hexagonal_example(self, config: ProjectConfig, base_path: Path) -> None:
        """Generate example code with inbound/domain/outbound structure."""
        server_path = base_path / "server"

        print("[cyan]Generating hexagonal architecture example (inbound/domain/outbound)...[/cyan]")

        # ╔═══════════════════════════════════════════════════════════════╗
        # ║                     DOMAIN LAYER                              ║
        # ╚═══════════════════════════════════════════════════════════════╝

        # Domain Model: Entity
        entity_code = '''import { randomUUID } from 'crypto';

/**
 * Domain Entity - Core business object.
 * Contains business logic and is independent of infrastructure.
 */
export class Example {
  constructor(id, name, description) {
    this.id = id;
    this.name = name;
    this.description = description;
  }

  static create(name, description) {
    return new Example(randomUUID(), name, description);
  }

  updateDetails(name, description) {
    this.name = name;
    this.description = description;
  }
}
'''
        self._write_file(server_path, "src/domain/model/Example.js", entity_code)
        self._write_file(server_path, "src/domain/model/index.js", "export { Example } from './Example.js';\n")

        # Domain Service
        domain_service_code = '''import { Example } from '../model/index.js';

/**
 * Domain Service - Contains business logic.
 * Uses repository interfaces (ports) for data access.
 */
export class ExampleService {
  constructor(exampleRepository) {
    this.exampleRepository = exampleRepository;
  }

  async createExample(name, description) {
    const example = Example.create(name, description);
    return this.exampleRepository.save(example);
  }

  async findById(id) {
    return this.exampleRepository.findById(id);
  }

  async findAll() {
    return this.exampleRepository.findAll();
  }

  async deleteById(id) {
    return this.exampleRepository.deleteById(id);
  }
}
'''
        self._write_file(server_path, "src/domain/service/ExampleService.js", domain_service_code)
        self._write_file(server_path, "src/domain/service/index.js", "export { ExampleService } from './ExampleService.js';\n")

        # Domain Repository Interface (Port)
        repository_interface_code = '''/**
 * Repository Interface (Port) - Defines data access contract.
 * Implementation is in outbound/persistence layer.
 *
 * @interface ExampleRepository
 * @method save(example) - Promise<Example>
 * @method findById(id) - Promise<Example|null>
 * @method findAll() - Promise<Example[]>
 * @method deleteById(id) - Promise<void>
 */
export const ExampleRepository = {
  save: async (example) => { throw new Error('Not implemented'); },
  findById: async (id) => { throw new Error('Not implemented'); },
  findAll: async () => { throw new Error('Not implemented'); },
  deleteById: async (id) => { throw new Error('Not implemented'); },
};
'''
        self._write_file(server_path, "src/domain/repository/ExampleRepository.js", repository_interface_code)
        self._write_file(server_path, "src/domain/repository/index.js", "export { ExampleRepository } from './ExampleRepository.js';\n")

        # Domain Client Interface (Port for external services)
        client_interface_code = '''/**
 * Service Client Interface (Port) - For calling external web services.
 * Implementation is in outbound/restclient layer.
 *
 * @interface ExternalServiceClient
 * @method fetchExternalData(resourceId) - Promise<Object|null>
 * @method notifyExternalService(eventType, payload) - Promise<void>
 */
export const ExternalServiceClient = {
  fetchExternalData: async (resourceId) => { throw new Error('Not implemented'); },
  notifyExternalService: async (eventType, payload) => { throw new Error('Not implemented'); },
};
'''
        self._write_file(server_path, "src/domain/client/ExternalServiceClient.js", client_interface_code)
        self._write_file(server_path, "src/domain/client/index.js", "export { ExternalServiceClient } from './ExternalServiceClient.js';\n")

        # Domain MessageProducer Interface (Port)
        message_producer_interface_code = '''/**
 * Message Producer Interface (Port) - For publishing events.
 * Implementation is in outbound/messaging layer (e.g., RabbitMQ).
 *
 * @interface ExampleEventProducer
 * @method publishExampleCreated(exampleId, name) - Promise<void>
 * @method publishExampleDeleted(exampleId) - Promise<void>
 */
export const ExampleEventProducer = {
  publishExampleCreated: async (exampleId, name) => { throw new Error('Not implemented'); },
  publishExampleDeleted: async (exampleId) => { throw new Error('Not implemented'); },
};
'''
        self._write_file(server_path, "src/domain/messaging/ExampleEventProducer.js", message_producer_interface_code)
        self._write_file(server_path, "src/domain/messaging/index.js", "export { ExampleEventProducer } from './ExampleEventProducer.js';\n")

        # ╔═══════════════════════════════════════════════════════════════╗
        # ║                    INBOUND LAYER                              ║
        # ╚═══════════════════════════════════════════════════════════════╝

        # Inbound DTOs
        dto_code = '''/**
 * Request DTO - Data transfer object for incoming requests.
 */
export function createExampleRequest(name, description) {
  return { name, description };
}

/**
 * Response DTO - Data transfer object for outgoing responses.
 */
export function toExampleResponse(example) {
  return {
    id: example.id,
    name: example.name,
    description: example.description,
  };
}
'''
        self._write_file(server_path, "src/inbound/dto/ExampleDto.js", dto_code)
        self._write_file(server_path, "src/inbound/dto/index.js", "export { createExampleRequest, toExampleResponse } from './ExampleDto.js';\n")

        # Inbound REST Controller
        controller_code = '''import { Router } from 'express';
import { toExampleResponse } from '../dto/index.js';

/**
 * REST Controller (Inbound Adapter) - Handles HTTP requests.
 * Converts DTOs to domain objects and delegates to domain service.
 */
export function createExampleController(exampleService) {
  const router = Router();

  // GET /api/examples
  router.get('/', async (req, res, next) => {
    try {
      const examples = await exampleService.findAll();
      res.json(examples.map(toExampleResponse));
    } catch (error) {
      next(error);
    }
  });

  // GET /api/examples/:id
  router.get('/:id', async (req, res, next) => {
    try {
      const example = await exampleService.findById(req.params.id);
      if (!example) {
        return res.status(404).json({ error: 'Example not found' });
      }
      res.json(toExampleResponse(example));
    } catch (error) {
      next(error);
    }
  });

  // POST /api/examples
  router.post('/', async (req, res, next) => {
    try {
      const { name, description } = req.body;
      const created = await exampleService.createExample(name, description);
      res.status(201).json(toExampleResponse(created));
    } catch (error) {
      next(error);
    }
  });

  // DELETE /api/examples/:id
  router.delete('/:id', async (req, res, next) => {
    try {
      await exampleService.deleteById(req.params.id);
      res.status(204).send();
    } catch (error) {
      next(error);
    }
  });

  return router;
}
'''
        self._write_file(server_path, "src/inbound/rest/ExampleController.js", controller_code)
        self._write_file(server_path, "src/inbound/rest/index.js", "export { createExampleController } from './ExampleController.js';\n")

        # Inbound Message Consumer
        message_consumer_code = '''/**
 * Message Consumer (Inbound Adapter) - Handles incoming messages.
 * Example: RabbitMQ with amqplib or Kafka with kafkajs
 */
export class ExampleMessageConsumer {
  constructor(exampleService) {
    this.exampleService = exampleService;
  }

  /**
   * Handle incoming message from queue
   * @param {string} message - Raw message from broker
   */
  async handleMessage(message) {
    try {
      const event = JSON.parse(message);
      console.log('Received event:', event);

      // Delegate to domain service based on event type
      switch (event.type) {
        case 'CREATE_EXAMPLE':
          await this.exampleService.createExample(event.name, event.description);
          break;
        case 'DELETE_EXAMPLE':
          await this.exampleService.deleteById(event.id);
          break;
        default:
          console.warn('Unknown event type:', event.type);
      }
    } catch (error) {
      console.error('Error processing message:', error);
    }
  }
}
'''
        self._write_file(server_path, "src/inbound/messaging/ExampleMessageConsumer.js", message_consumer_code)
        self._write_file(server_path, "src/inbound/messaging/index.js", "export { ExampleMessageConsumer } from './ExampleMessageConsumer.js';\n")

        # Inbound Security Middleware
        security_code = '''/**
 * Security Middleware (Inbound) - Authentication and authorization.
 * Example: JWT validation, API key check, etc.
 */

/**
 * Authentication middleware - validates JWT token
 */
export function authMiddleware(req, res, next) {
  const authHeader = req.headers.authorization;

  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'No token provided' });
  }

  const token = authHeader.substring(7);

  // TODO: Validate JWT token
  // const decoded = jwt.verify(token, process.env.JWT_SECRET);
  // req.user = decoded;

  next();
}

/**
 * Authorization middleware - checks user roles
 */
export function requireRole(...roles) {
  return (req, res, next) => {
    // if (!req.user || !roles.includes(req.user.role)) {
    //   return res.status(403).json({ error: 'Forbidden' });
    // }
    next();
  };
}
'''
        self._write_file(server_path, "src/inbound/security/authMiddleware.js", security_code)
        self._write_file(server_path, "src/inbound/security/index.js", "export { authMiddleware, requireRole } from './authMiddleware.js';\n")

        # ╔═══════════════════════════════════════════════════════════════╗
        # ║                   OUTBOUND LAYER                              ║
        # ╚═══════════════════════════════════════════════════════════════╝

        # Outbound Persistence: Repository Implementation
        persistence_impl_code = '''/**
 * Repository Implementation (Outbound Adapter) - In-Memory/Database persistence.
 * Implements the domain repository interface.
 */
export class ExampleRepositoryImpl {
  constructor() {
    // In-memory storage (replace with database in production)
    this.storage = new Map();
  }

  async save(example) {
    this.storage.set(example.id, example);
    return example;
  }

  async findById(id) {
    return this.storage.get(id) || null;
  }

  async findAll() {
    return Array.from(this.storage.values());
  }

  async deleteById(id) {
    this.storage.delete(id);
  }
}
'''
        self._write_file(server_path, "src/outbound/persistence/ExampleRepositoryImpl.js", persistence_impl_code)
        self._write_file(server_path, "src/outbound/persistence/index.js", "export { ExampleRepositoryImpl } from './ExampleRepositoryImpl.js';\n")

        # Outbound REST Client: External Service Client Implementation
        rest_client_impl_code = '''/**
 * REST Client Implementation (Outbound Adapter) - Calls external web services.
 * Implements the domain client interface.
 */
export class ExternalServiceClientImpl {
  constructor(baseUrl = 'https://api.example.com') {
    this.baseUrl = baseUrl;
  }

  async fetchExternalData(resourceId) {
    try {
      const response = await fetch(`${this.baseUrl}/resources/${resourceId}`);
      if (!response.ok) return null;
      return response.json();
    } catch (error) {
      console.error('Failed to fetch external data:', error);
      return null;
    }
  }

  async notifyExternalService(eventType, payload) {
    try {
      await fetch(`${this.baseUrl}/events`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ eventType, payload }),
      });
    } catch (error) {
      console.error('Failed to notify external service:', error);
    }
  }
}
'''
        self._write_file(server_path, "src/outbound/restclient/ExternalServiceClientImpl.js", rest_client_impl_code)
        self._write_file(server_path, "src/outbound/restclient/index.js", "export { ExternalServiceClientImpl } from './ExternalServiceClientImpl.js';\n")

        # Outbound Messaging: Message Producer Implementation
        messaging_impl_code = '''/**
 * Message Producer Implementation (Outbound Adapter) - Publishes events to message broker.
 * Implements the domain messaging interface.
 * Example: RabbitMQ with amqplib
 */
export class RabbitMQExampleProducer {
  constructor(channel = null) {
    this.channel = channel;
    this.exchange = 'example.exchange';
  }

  async publishExampleCreated(exampleId, name) {
    const message = JSON.stringify({
      event: 'EXAMPLE_CREATED',
      id: exampleId,
      name: name,
      timestamp: new Date().toISOString(),
    });

    // if (this.channel) {
    //   this.channel.publish(this.exchange, 'example.created', Buffer.from(message));
    // }
    console.log('Published event:', message);
  }

  async publishExampleDeleted(exampleId) {
    const message = JSON.stringify({
      event: 'EXAMPLE_DELETED',
      id: exampleId,
      timestamp: new Date().toISOString(),
    });

    // if (this.channel) {
    //   this.channel.publish(this.exchange, 'example.deleted', Buffer.from(message));
    // }
    console.log('Published event:', message);
  }
}
'''
        self._write_file(server_path, "src/outbound/messaging/RabbitMQExampleProducer.js", messaging_impl_code)
        self._write_file(server_path, "src/outbound/messaging/index.js", "export { RabbitMQExampleProducer } from './RabbitMQExampleProducer.js';\n")

        # ╔═══════════════════════════════════════════════════════════════╗
        # ║                      CONFIG & MAIN                            ║
        # ╚═══════════════════════════════════════════════════════════════╝

        # Config
        config_code = '''export const config = {
  port: process.env.PORT || 3000,
  nodeEnv: process.env.NODE_ENV || 'development',
  // Add more configuration here
};
'''
        self._write_file(server_path, "src/config/index.js", config_code)

        # Main Application Entry Point
        index_code = '''import express from 'express';
import { config } from './config/index.js';

// Domain
import { ExampleService } from './domain/service/index.js';

// Inbound
import { createExampleController } from './inbound/rest/index.js';

// Outbound
import { ExampleRepositoryImpl } from './outbound/persistence/index.js';

const app = express();

// Middleware
app.use(express.json());

// ══════════════════════════════════════════════════════════════════
// Dependency Injection: Wire up the hexagonal architecture
// ══════════════════════════════════════════════════════════════════

// Outbound adapters (driven)
const exampleRepository = new ExampleRepositoryImpl();

// Domain services
const exampleService = new ExampleService(exampleRepository);

// Inbound adapters (driving)
const exampleController = createExampleController(exampleService);

// ══════════════════════════════════════════════════════════════════
// Routes
// ══════════════════════════════════════════════════════════════════

app.use('/api/examples', exampleController);

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'ok' });
});

// Error handling middleware
app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(500).json({ error: 'Internal Server Error' });
});

// Start server
app.listen(config.port, () => {
  console.log(`Server running on http://localhost:${config.port}`);
  console.log(`API available at http://localhost:${config.port}/api/examples`);
});
'''
        self._write_file(server_path, "src/index.js", index_code)

        print("[green]Generated hexagonal architecture example![/green]")
        print("[dim]  INBOUND:  dto, rest (Controller), messaging (Consumer), security[/dim]")
        print("[dim]  DOMAIN:   model (Entity), service, repository, client, messaging (interfaces)[/dim]")
        print("[dim]  OUTBOUND: persistence (RepoImpl), restclient (ClientImpl), messaging (ProducerImpl)[/dim]")

    def _write_file(self, base_path: Path, relative_path: str, content: str) -> None:
        file_path = base_path / relative_path
        file_path.parent.mkdir(parents=True, exist_ok=True)
        with open(file_path, "w") as f:
            f.write(content)

    def install_dependencies(self, base_path: Path) -> None:
        server_path = base_path / "server"
        print("[yellow]Running npm install for server...[/yellow]")
        try:
            subprocess.run(["npm", "install"], cwd=server_path, shell=True, check=True)
            print("[green]Server dependencies installed successfully![/green]")
        except subprocess.CalledProcessError:
            print("[red]Failed to install dependencies. Do you have 'npm' installed?[/red]")
        except Exception as e:
            print(f"[red]Error during installation: {e}[/red]")
