import json
import subprocess
import os
from typing import List
from pathlib import Path

from .base import ArchitectureStrategy
from skelly.core.models import ProjectConfig

class ExpressStandardStrategy(ArchitectureStrategy):
    def get_architecture_name(self) -> str:
        return "Express Standard Architecture"
    
    def get_required_folders(self) -> List[str]:
        return [
            "src/api/routes",
            "src/api/controllers",
            "src/api/middlewares",
            "src/services",
            "src/models",
            "src/loaders",
            "src/config",
            "src/utils"
        ]

    def initialize_project(self, config: ProjectConfig, base_path: Path) -> None:
        # dependencies
        dependencies = {
            "express": "^4.18.2"
        }
        
        # dev dependencies
        for lib_entry in config.backend_libraries:
            libs = lib_entry.split(" ")
            for lib in libs:
                if lib.strip():
                    dependencies[lib] = "latest"

        package_json = {
            "name": config.name.lower(),
            "version": "0.1.0",
            "description": "Generated by Skelly",
            "main": "src/index.js",
            "scripts": {
                "start": "node src/index.js",
                "dev": "nodemon src/index.js"
            },
            "dependencies": dependencies
        }

        # creating package.json file
        package_json_path = base_path / "package.json"
        with open(package_json_path, "w") as f:
            json.dump(package_json, f, indent=2)
        
        print(f"[cyan]Created package.json with dependencies: {', '.join(dependencies.keys())}[/cyan]")

        # running npm install
        print("[yellow]Running npm install...[/yellow]")
        try:
            subprocess.run(["npm", "install"], cwd=base_path, shell=True, check=True)
            print("[green]Dependencies installed successfully![/green]")
        except subprocess.CalledProcessError:
            print("[red]Failed to install dependencies. Do you have 'npm' installed?[/red]")
        except Exception as e:
            print(f"[red]Error during installation: {e}[/red]")